<?php

return [
    'shop_title' => 'QQ发卡——基于PHP + MySQL打造的商城建站系统',
    'shop_pet_name' => '发卡吧',
    'beian' => '',
    'version' => '1648775325',
    'min_cashout' => '0',
    'max_cashout_num' => '3',
    'cashout_charged' => '1',
    'tourist_buy' => '1',
    'login' => '1',
    'register' => '1',
    'statistics' => '',
    'diy_name' => '商品购买',
    'buy_account' => '0',
    'buy_password' => '0',
    'tip_account' => '',
    'tip_password' => '游客查询订单时的凭证',
    'eject_goods' => '',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_verify_type' => '2',
    'mail_smtp_port' => '465',
    'mail_smtp_pass' => '',
    'mail_smtp_user' => '红盟云卡',
    'mail_from' => '',
    'admin_order_email' => '0',
    'user_order_email' => '0',
    'ico' => 'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.ixintu.com%2Fdownload%2Fjpg%2F201910%2Fbc00b9328498cb238cb3b9b783e19aa5.jpg%21con&refer=http%3A%2F%2Fimg.ixintu.com&app=2002&size=f9999',
    'cdk_order' => 'asc',
];
